<?php

use Illuminate\Database\Seeder;

class TinTuyenDungSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('tintuyendung')->truncate();
        
        $data = [
        	[
        		'kinang' => '["1","2","3","4","5"]',
        		'nganh' => 'Lập trình viên Back End',
        		'soluong' => 20, 
                'tinhthanhpho' => '["TP Hồ Chí Minh","Tiền Giang","Hưng Yên"]',  
        		'idNTD' => 1,        		
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 1 đến 2 năm',
                'hantuyendung' => '2020-06-30',
                'bangcap' => 'Đại học',                
                'mucluong' => 'Dưới 3 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Full Time',
                'congkhai' => 1,
        	],
            [
                'kinang' => '["6","7","8","9","10"]',
                'nganh' => 'Lập trình viên Front End',
                'soluong' => 15, 
                'tinhthanhpho' => '["TP Hồ Chí Minh","Cà Mau","Bến Tre"]',
                'idNTD' => 1,     
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 2 đến 3 năm',
                'hantuyendung' => '2020-07-15',
                'bangcap' => 'Đại học',
                'mucluong' => '3-5 triệu',
                'motacv' => 'Lập trình client',
                'quyenloi' => 'Lương tháng 13',          
                'trangthailv' => 'Part Time',
                'congkhai' => 1,
            ], 
            [
                'kinang' => '["11","12"]',
                'nganh' => 'Lập trình viên C++',
                'soluong' => 10, 
                'tinhthanhpho' => '["Long An","Hà Nội","Vũng Tàu"]',         
                'idNTD' => 1,            
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 2 đến 3 năm',
                'hantuyendung' => '2020-08-01',
                'bangcap' => 'Không yêu cầu',
                'mucluong' => '7-10 triệu',
                'motacv' => 'Lập trình nhúng',
                'quyenloi' => 'Lương tháng 13',   
                'trangthailv' => 'Full Time',
                'congkhai' => 1,
            ], 
            [
                'kinang' => '["16","17","18","19","20"]',
                'nganh' => 'Lập trình viên Android',
                'soluong' => 5, 
                'tinhthanhpho' => '["Vĩnh Long","Đồng Nai","Đà Nẵng"]',           
                'idNTD' => 1,               
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 3 đến 4 năm',
                'hantuyendung' => '2020-06-30',
                'bangcap' => 'Cao đẳng',
                'mucluong' => '5-7 triệu',
                'motacv' => 'Lập trình Mobile',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Part Time',
                'congkhai' => 1,
            ], 
            [
                'kinang' => '["21","22","23","24"]',
                'nganh' => 'Lập trình viên Back End',
                'soluong' => 30, 
                'tinhthanhpho' => '["Khánh Hoà","Cần Thơ","Lâm Đồng"]',         
                'idNTD' => 2,               
                'gioitinh' => 'Bất kì',
                'kinhnghiem' => 'Từ 2 đến 3 năm',
                'hantuyendung' => '2020-07-30',
                'bangcap' => 'Cao đẳng',
                'mucluong' => '40-50 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Full Time',
                'congkhai' => 1,
            ],
            [
                'kinang' => '["31","32","33"]',
                'nganh' => 'Lập trình viên OOP',
                'soluong' => 20, 
                'tinhthanhpho' => '["TP Hồ Chí Minh","Hà Nội","Nghệ An"]',       
                'idNTD' => 2,               
                'gioitinh' => 'Bất kì',
                'kinhnghiem' => 'Từ 4 đến 5 năm',
                'hantuyendung' => '2020-07-30',
                'bangcap' => 'Cao học',
                'mucluong' => '15-20 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Part Time',
                'congkhai' => 1,
            ],
            [
                'kinang' => '["13"]',
                'nganh' => 'Lập trình viên C#',
                'soluong' => 10, 
                'tinhthanhpho' => '["TP Hồ Chí Minh","Hà Nội","Đà Nẵng"]',              
                'idNTD' => 2,               
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Trên 5 năm',
                'hantuyendung' => '2020-08-30',
                'bangcap' => 'Đại học',
                'mucluong' => 'Trên 50 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Part Time',
                'congkhai' => 1,
            ],
            [
                'kinang' => '["1","4","7","2","3"]',
                'nganh' => 'Kỹ sư cầu nối',
                'soluong' => 20, 
                'tinhthanhpho' => '["TP Hồ Chí Minh","Nam Định","Đồng Tháp"]',  
                'idNTD' => 1,               
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 1 đến 2 năm',
                'hantuyendung' => '2020-07-30',
                'bangcap' => 'Đại học',
                'mucluong' => 'Dưới 3 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Part Time',
                'congkhai' => 1,
            ],
            [
                'kinang' => '["12","14","27","22","33"]',
                'nganh' => 'Full Stack Web Developer',
                'soluong' => 20, 
                'tinhthanhpho' => '["Long An","Nam Định","Vĩnh Long"]',  
                'idNTD' => 1,               
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 3 đến 4 năm',
                'hantuyendung' => '2020-07-30',
                'bangcap' => 'Đại học',
                'mucluong' => '20-25 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Full Time',
                'congkhai' => 1,
            ],
            [
                'kinang' => '["16","12","14","21"]',
                'nganh' => 'Lập trình viên Games',
                'soluong' => 20, 
                'tinhthanhpho' => '["Long An","Nam Định","Vĩnh Long"]',  
                'idNTD' => 1,               
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 3 đến 4 năm',
                'hantuyendung' => '2020-07-30',
                'bangcap' => 'Đại học',
                'mucluong' => '20-25 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Full Time',
                'congkhai' => 1,
            ],
            [
                'kinang' => '["12","14","22","33"]',
                'nganh' => 'Lập trình viên Ruby',
                'soluong' => 20, 
                'tinhthanhpho' => '["Thanh Hoá","Đồng Nai","Vĩnh Long"]',  
                'idNTD' => 1,               
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 3 đến 4 năm',
                'hantuyendung' => '2020-07-30',
                'bangcap' => 'Đại học',
                'mucluong' => '20-25 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Full Time',
                'congkhai' => 1,
            ],
            [
                'kinang' => '["21","25","17","12","13"]',
                'nganh' => 'Quản trị cơ sở dữ liệu',
                'soluong' => 25, 
                'tinhthanhpho' => '["Nghệ An","Bình Phước"]',  
                'idNTD' => 1,               
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 3 đến 4 năm',
                'hantuyendung' => '2020-07-30',
                'bangcap' => 'Đại học',
                'mucluong' => '20-25 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Full Time',
                'congkhai' => 1,
            ],
            [
                'kinang' => '["25","11","22"]',
                'nganh' => 'Python Web Developer',
                'soluong' => 45, 
                'tinhthanhpho' => '["Huế"]',  
                'idNTD' => 1,               
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 3 đến 4 năm',
                'hantuyendung' => '2020-08-15',
                'bangcap' => 'Đại học',
                'mucluong' => '20-25 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Full Time',
                'congkhai' => 1,
            ],
            [
                'kinang' => '["12","14","25","22"]',
                'nganh' => 'Lập trình viên iOS',
                'soluong' => 45, 
                'tinhthanhpho' => '["Long An","Lào Cai"]',  
                'idNTD' => 1,               
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 4 đến 5 năm',
                'hantuyendung' => '2020-08-15',
                'bangcap' => 'Đại học',
                'mucluong' => '25-30 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Full Time',
                'congkhai' => 1,
            ],
            [
                'kinang' => '["2","4","3","1"]',
                'nganh' => 'Lập trình viên Embedded',
                'soluong' => 40, 
                'tinhthanhpho' => '["Phú Thọ","Tây Ninh"]',  
                'idNTD' => 1,               
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 3 đến 4 năm',
                'hantuyendung' => '2020-08-30',
                'bangcap' => 'Đại học',
                'mucluong' => '20-25 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Full Time',
                'congkhai' => 1,
            ],
            [
                'kinang' => '["8","6","4","2"]',
                'nganh' => 'Lập trình viên .NET',
                'soluong' => 15, 
                'tinhthanhpho' => '["Long An","Tuyên Quang","Lai Châu"]',  
                'idNTD' => 1,               
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 3 đến 4 năm',
                'hantuyendung' => '2020-07-15',
                'bangcap' => 'Đại học',
                'mucluong' => '20-25 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Full Time',
                'congkhai' => 1,
            ],
            [
                'kinang' => '["12","14","25","22"]',
                'nganh' => 'Lập trình viên iOS',
                'soluong' => 5, 
                'tinhthanhpho' => '["Long An","Lào Cai"]',  
                'idNTD' => 1,               
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 4 đến 5 năm',
                'hantuyendung' => '2020-07-30',
                'bangcap' => 'Đại học',
                'mucluong' => '25-30 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Full Time',
                'congkhai' => 1,
            ],
            [
                'kinang' => '["2","4","5"]',
                'nganh' => 'Lập trình viên .NET',
                'soluong' => 10, 
                'tinhthanhpho' => '["Lào Cai"]',  
                'idNTD' => 1,               
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 4 đến 5 năm',
                'hantuyendung' => '2020-08-15',
                'bangcap' => 'Đại học',
                'mucluong' => '20-25 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Part Time',
                'congkhai' => 1,
            ],
            [
                'kinang' => '["7","9","11","13"]',
                'nganh' => 'Lập trình viên SQL',
                'soluong' => 15, 
                'tinhthanhpho' => '["Long An"]',  
                'idNTD' => 1,               
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 4 đến 5 năm',
                'hantuyendung' => '2020-08-30',
                'bangcap' => 'Cao học',
                'mucluong' => '25-30 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Full Time',
                'congkhai' => 1,
            ],
            [
                'kinang' => '["13","15","26","23"]',
                'nganh' => 'Lập trình viên Unity',
                'soluong' => 30, 
                'tinhthanhpho' => '["Hà Nội","Lào Cai"]',  
                'idNTD' => 1,               
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 4 đến 5 năm',
                'hantuyendung' => '2020-07-30',
                'bangcap' => 'Cao học',
                'mucluong' => '25-30 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Full Time',
                'congkhai' => 1,
            ],
            [
                'kinang' => '["31","32","33","34","35"]',
                'nganh' => 'Lập trình viên PHP',
                'soluong' => 25, 
                'tinhthanhpho' => '["Cao Bằng","Lào Cai"]',  
                'idNTD' => 1,               
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 4 đến 5 năm',
                'hantuyendung' => '2020-07-30',
                'bangcap' => 'Cao học',
                'mucluong' => '25-30 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Full Time',
                'congkhai' => 1,
            ],
            [
                'kinang' => '["35","36","37","38","39"]',
                'nganh' => 'Lập trình viên PHP',
                'soluong' => 15, 
                'tinhthanhpho' => '["Cao Bằng","Bắc Ninh"]',  
                'idNTD' => 1,               
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 4 đến 5 năm',
                'hantuyendung' => '2020-07-30',
                'bangcap' => 'Cao học',
                'mucluong' => '25-30 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Full Time',
                'congkhai' => 1,
            ],
            [
                'kinang' => '["30","36","38","39"]',
                'nganh' => 'Lập trình viên OOP',
                'soluong' => 35, 
                'tinhthanhpho' => '["Đắc Lắc","Đắk Nông"]',  
                'idNTD' => 1,               
                'gioitinh' => 'Nam',
                'kinhnghiem' => 'Từ 4 đến 5 năm',
                'hantuyendung' => '2020-07-30',
                'bangcap' => 'Cao học',
                'mucluong' => '25-30 triệu',
                'motacv' => 'Lập trình server',
                'quyenloi' => 'Lương tháng 13',
                'trangthailv' => 'Full Time',
                'congkhai' => 1,
            ],
        ];

        foreach ($data as $v) {
        	DB::table('tintuyendung')->insert(
        		[
        			'kinang' => $v['kinang'],
        			'nganh' => $v['nganh'],
        			'tinhthanhpho' => $v['tinhthanhpho'],
        			'soluong' => $v['soluong'],
                    'gioitinh' => $v['gioitinh'],
                    'kinhnghiem' => $v['kinhnghiem'],
                    'mucluong' => $v['mucluong'],
                    'bangcap' => $v['bangcap'],
                    'capbac' => 'Nhân viên',
                    'hantuyendung' => $v['hantuyendung'],
                    'trangthailv' => $v['trangthailv'],
                    'congkhai' => $v['congkhai'],
                    // 'motacv' => json_encode($v['motacv'],JSON_UNESCAPED_UNICODE),
                    // 'quyenloi' => json_encode($v['quyenloi'],JSON_UNESCAPED_UNICODE),
                    'motacv' => '["'.$v['motacv'].'"]',
                    'quyenloi' => '["'.$v['quyenloi'].'"]',
        			'idNTD' => $v['idNTD'],        			
        			'created_at' => Carbon\Carbon::now()->toDateTimeString(),        			
        			'updated_at' => Carbon\Carbon::now()->toDateTimeString(),        			
        		]
        	);
        }      

        Schema::enableForeignKeyConstraints();
    }
}
